# Generated by Django 5.2.6 on 2026-08-23 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding_signature',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('CHAT', 'Chat模型'), ('EMBEDDING', 'Embedding模型')], max_length=20)),
                ('base_url', models.URLField(max_length=500)),
                ('model_name', models.CharField(max_length=200)),
                ('encrypted_api_key', models.TextField()),
                ('api_key_last4', models.CharField(blank=True, max_length=4)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('last_test_status', models.CharField(choices=[('UNTESTED', '未测试'), ('SUCCESS', '连接成功'), ('FAILURE', '连接失败')], default='UNTESTED', max_length=20)),
                ('last_test_message', models.CharField(blank=True, max_length=200)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('embedding_dimension', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='chat_model_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='chat_knowledge_bases', to='api.modelconfig'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='embedding_model_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='embedding_knowledge_bases', to='api.modelconfig'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_model_config_name'),
        ),
    ]
