# Generated by Django 5.2.6 on 2026-08-23 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_embedding_signature_modelconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='max_context_chars',
            field=models.PositiveIntegerField(default=6000),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='no_answer_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='retrieval_mode',
            field=models.CharField(choices=[('VECTOR', '纯向量'), ('HYBRID', '混合检索')], default='VECTOR', max_length=10),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='retrieval_top_k',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='similarity_threshold',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='system_prompt',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='vector_weight',
            field=models.FloatField(default=1),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(('retrieval_top_k__gte', 1), ('retrieval_top_k__lte', 20)), name='knowledge_retrieval_top_k_range'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(('similarity_threshold__gte', 0), ('similarity_threshold__lte', 1)), name='knowledge_similarity_threshold_range'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(('vector_weight__gte', 0), ('vector_weight__lte', 1)), name='knowledge_vector_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(('max_context_chars__gte', 1000), ('max_context_chars__lte', 30000)), name='knowledge_context_chars_range'),
        ),
    ]
