# Generated by Django 5.2.6 on 2026-08-23 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_knowledgebase_max_context_chars_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', '执行中'), ('SUCCESS', '成功'), ('FAILURE', '失败'), ('LIMIT_REACHED', '达到步骤上限'), ('CANCELLED', '已取消')], default='RUNNING', max_length=20)),
                ('step_count', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=50)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField()),
                ('sequence', models.PositiveSmallIntegerField()),
                ('tool_call_id', models.CharField(max_length=200)),
                ('tool_name', models.CharField(max_length=100)),
                ('arguments', models.JSONField(default=dict)),
                ('result_summary', models.CharField(blank=True, default='', max_length=500)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('RUNNING', '执行中'), ('SUCCESS', '成功'), ('FAILURE', '失败'), ('REJECTED', '已拒绝')], default='RUNNING', max_length=20)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=50)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['step', 'sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='agent_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='agent_max_steps',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='agent_system_prompt',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='enabled_tools',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(('agent_max_steps__gte', 1), ('agent_max_steps__lte', 10)), name='knowledge_agent_max_steps_range'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='assistant_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_run_as_assistant', to='api.message'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='api.conversation'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='user_message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_run_as_user', to='api.message'),
        ),
        migrations.AddField(
            model_name='toolexecution',
            name='agent_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='api.agentrun'),
        ),
        migrations.AddConstraint(
            model_name='toolexecution',
            constraint=models.UniqueConstraint(fields=('agent_run', 'step', 'sequence'), name='unique_agent_tool_step_sequence'),
        ),
    ]
