# Generated by Django 5.2.6 on 2026-08-25 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_agentrun_toolexecution_knowledgebase_agent_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('UPLOAD', '首次上传'), ('REPROCESS', '重新处理')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', '等待处理'), ('PROCESSING', '处理中'), ('RETRYING', '等待重试'), ('SUCCESS', '处理成功'), ('FAILURE', '处理失败'), ('ENQUEUE_FAILED', '任务投递失败'), ('CANCEL_REQUESTED', '正在取消'), ('CANCELLED', '已取消')], default='PENDING', max_length=30)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('current_stage', models.CharField(choices=[('WAITING', '等待处理'), ('READING', '正在解析'), ('SPLITTING', '正在切片'), ('EMBEDDING', '正在生成向量'), ('SAVING', '正在保存'), ('DONE', '处理完成'), ('FAILED', '处理失败'), ('CANCELLING', '正在取消'), ('CANCELLED', '已取消')], default='WAITING', max_length=30)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_tasks', to='api.document')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='document_task_progress_range'), models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'PROCESSING', 'RETRYING', 'CANCEL_REQUESTED'))), fields=('document',), name='unique_active_document_processing_task'), models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('document', 'idempotency_key'), name='unique_document_processing_idempotency_key')],
            },
        ),
    ]
