# Generated by Django 5.2.6 on 2026-09-01 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_documentprocessingtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='fusion_method',
            field=models.CharField(choices=[('WEIGHTED', '加权融合'), ('RRF', 'RRF排名融合')], default='WEIGHTED', max_length=10),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='keyword_candidate_k',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='rerank_candidate_k',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='rerank_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='rrf_k',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='vector_candidate_k',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(('vector_candidate_k__gte', 1), ('vector_candidate_k__lte', 100)), name='knowledge_vector_candidate_k_range'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(('keyword_candidate_k__gte', 1), ('keyword_candidate_k__lte', 100)), name='knowledge_keyword_candidate_k_range'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(('rrf_k__gte', 1), ('rrf_k__lte', 200)), name='knowledge_rrf_k_range'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(('rerank_candidate_k__gte', 1), ('rerank_candidate_k__lte', 50)), name='knowledge_rerank_candidate_k_range'),
        ),
    ]
