# Generated by Django 5.2.6 on 2026-09-06 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_knowledgebase_fusion_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='access_type',
            field=models.CharField(choices=[('KNOWLEDGE', '知识库后台'), ('PREVIEW', '应用预览'), ('PUBLIC_WEB', '公开页面'), ('EMBED', '嵌入页面'), ('API', '第三方API')], default='KNOWLEDGE', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='visitor_id_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='knowledge_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='api.knowledgebase'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('DISABLED', '已停用')], default='DRAFT', max_length=20)),
                ('system_prompt', models.TextField(blank=True, default='', max_length=4000)),
                ('welcome_message', models.CharField(blank=True, default='', max_length=500)),
                ('suggested_questions', models.JSONField(blank=True, default=list)),
                ('show_references', models.BooleanField(default=True)),
                ('agent_enabled', models.BooleanField(default=False)),
                ('agent_max_steps', models.PositiveSmallIntegerField(default=5)),
                ('agent_system_prompt', models.TextField(blank=True, default='', max_length=4000)),
                ('enabled_tools', models.JSONField(blank=True, default=list)),
                ('global_top_k', models.PositiveSmallIntegerField(default=5)),
                ('max_context_chars', models.PositiveIntegerField(default=6000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='applications', to='api.modelconfig')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='api.application'),
        ),
        migrations.CreateModel(
            name='ApplicationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key_prefix', models.CharField(db_index=True, max_length=32, unique=True)),
                ('secret_digest', models.CharField(max_length=64)),
                ('last4', models.CharField(max_length=4)),
                ('enabled', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='api.application')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('weight', models.FloatField(default=1.0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='api.application')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_links', to='api.knowledgebase')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPublicAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('token_prefix', models.CharField(db_index=True, max_length=32, unique=True)),
                ('token_digest', models.CharField(max_length=64)),
                ('token_last4', models.CharField(max_length=4)),
                ('allowed_frame_origins', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_access', to='api.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('config_snapshot', models.JSONField(default=dict)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.application')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_application_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=64, unique=True)),
                ('access_type', models.CharField(choices=[('KNOWLEDGE', '知识库后台'), ('PREVIEW', '应用预览'), ('PUBLIC_WEB', '公开页面'), ('EMBED', '嵌入页面'), ('API', '第三方API')], max_length=20)),
                ('client_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('RUNNING', '执行中'), ('SUCCESS', '成功'), ('FAILURE', '失败'), ('REJECTED', '拒绝')], default='RUNNING', max_length=20)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('first_token_latency_ms', models.PositiveIntegerField(default=0)),
                ('retrieval_latency_ms', models.PositiveIntegerField(default=0)),
                ('model_latency_ms', models.PositiveIntegerField(default=0)),
                ('total_latency_ms', models.PositiveIntegerField(default=0)),
                ('retrieved_paragraph_count', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='api.application')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_access_logs', to='api.conversation')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='api.applicationcredential')),
                ('application_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='api.applicationversion')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='current_published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_applications', to='api.applicationversion'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='application_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='api.applicationversion'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('application__isnull', True), ('knowledge_base__isnull', False), ('owner__isnull', False), ('visitor_id_hash', '')), models.Q(('application__isnull', False), ('knowledge_base__isnull', True), ('owner__isnull', False), ('visitor_id_hash', '')), models.Q(('application__isnull', False), ('knowledge_base__isnull', True), ('owner__isnull', True), models.Q(('visitor_id_hash', ''), _negated=True)), _connector='OR'), name='valid_conversation_scope'),
        ),
        migrations.AddConstraint(
            model_name='applicationknowledgebase',
            constraint=models.UniqueConstraint(fields=('application', 'knowledge_base'), name='unique_application_knowledge_base'),
        ),
        migrations.AddConstraint(
            model_name='applicationknowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0.1), ('weight__lte', 3.0)), name='application_knowledge_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='applicationversion',
            constraint=models.UniqueConstraint(fields=('application', 'version'), name='unique_application_version'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_application_name'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('global_top_k__gte', 1), ('global_top_k__lte', 20)), name='application_global_top_k_range'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('agent_max_steps__gte', 1), ('agent_max_steps__lte', 10)), name='application_agent_steps_range'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('max_context_chars__gte', 1000), ('max_context_chars__lte', 30000)), name='application_context_chars_range'),
        ),
    ]
