# Generated by Django 5.2.6 on 2026-09-09 04:23

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_conversation_access_type_conversation_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('heading_path', models.JSONField(blank=True, default=list)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('content_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('parser_version', models.CharField(blank=True, default='', max_length=30)),
                ('chunker_version', models.CharField(blank=True, default='', max_length=30)),
                ('source_block_ids', models.JSONField(blank=True, default=list)),
                ('structure_type', models.CharField(choices=[('TEXT', '正文'), ('TABLE', '表格'), ('CODE', '代码'), ('LIST', '列表'), ('MIXED', '混合')], default='TEXT', max_length=20)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='child_overlap_tokens',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='document',
            name='child_target_tokens',
            field=models.PositiveSmallIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='document',
            name='chunk_strategy',
            field=models.CharField(choices=[('LEGACY', '兼容切片'), ('PARENT_CHILD', '父子切片')], default='LEGACY', max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='chunker_version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='indexed_chunking_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='parent_chunk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='parent_max_tokens',
            field=models.PositiveSmallIntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='document',
            name='parser_type',
            field=models.CharField(choices=[('AUTO', '自动识别'), ('TXT', '纯文本'), ('MARKDOWN', 'Markdown'), ('PDF', 'PDF'), ('DOCX', 'DOCX')], default='AUTO', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='parser_version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='parsing_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='preserve_code_blocks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='preserve_tables',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='source_id',
            field=models.CharField(db_index=True, default=api.models.generate_document_source_id, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='document',
            name='source_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='chunk_type',
            field=models.CharField(choices=[('LEGACY', '兼容切片'), ('CHILD', '子切片')], default='LEGACY', max_length=20),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='chunker_version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='content_sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='heading_path',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='parser_version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='source_block_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='structure_type',
            field=models.CharField(choices=[('TEXT', '正文'), ('TABLE', '表格'), ('CODE', '代码'), ('LIST', '列表'), ('MIXED', '混合')], default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='token_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('parent_max_tokens__gte', 400), ('parent_max_tokens__lte', 4000)), name='document_parent_token_range'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('child_target_tokens__gte', 100), ('child_target_tokens__lte', 1200)), name='document_child_token_range'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('child_overlap_tokens__gte', 0), ('child_overlap_tokens__lte', 300)), name='document_overlap_token_range'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('child_overlap_tokens__lt', models.F('child_target_tokens'))), name='document_overlap_less_than_child'),
        ),
        migrations.AddField(
            model_name='documentsection',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.document'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='parent_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.documentsection'),
        ),
        migrations.AddConstraint(
            model_name='documentsection',
            constraint=models.UniqueConstraint(fields=('document', 'position'), name='unique_document_section_position'),
        ),
    ]
