# Generated by Django 5.2.6 on 2026-09-09 04:23

import api.models
from django.db import migrations, models


def assign_unique_source_ids(apps, schema_editor):
    Document = apps.get_model("api", "Document")
    for document in Document.objects.order_by("id").iterator():
        document.source_id = api.models.generate_document_source_id()
        document.save(update_fields=["source_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_documentsection_document_child_overlap_tokens_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_unique_source_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='document',
            name='source_id',
            field=models.CharField(db_index=True, default=api.models.generate_document_source_id, editable=False, max_length=80, unique=True),
        ),
    ]
