# Generated by Django 5.2.6 on 2026-09-10 09:39

from django.db import migrations


def backfill_personal_workspaces(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Organization = apps.get_model("api", "Organization")
    OrganizationMembership = apps.get_model("api", "OrganizationMembership")
    Workspace = apps.get_model("api", "Workspace")
    WorkspaceMembership = apps.get_model("api", "WorkspaceMembership")
    KnowledgeBase = apps.get_model("api", "KnowledgeBase")
    ModelConfig = apps.get_model("api", "ModelConfig")
    Application = apps.get_model("api", "Application")

    for user in User.objects.all().iterator():
        organization = Organization.objects.create(
            name=f"{user.username} 的个人组织"[:100],
            slug=f"personal-u{user.pk}",
            status="ACTIVE",
            created_by_id=user.pk,
        )
        OrganizationMembership.objects.create(
            organization_id=organization.pk,
            user_id=user.pk,
            role="OWNER",
            created_by_id=user.pk,
        )
        workspace = Workspace.objects.create(
            organization_id=organization.pk,
            name="默认工作空间",
            slug="default",
            status="ACTIVE",
            is_default=True,
            created_by_id=user.pk,
        )
        WorkspaceMembership.objects.create(
            workspace_id=workspace.pk,
            user_id=user.pk,
            role="ADMIN",
            created_by_id=user.pk,
        )
        KnowledgeBase.objects.filter(owner_id=user.pk, workspace_id__isnull=True).update(
            workspace_id=workspace.pk
        )
        ModelConfig.objects.filter(owner_id=user.pk, workspace_id__isnull=True).update(
            workspace_id=workspace.pk
        )
        Application.objects.filter(owner_id=user.pk, workspace_id__isnull=True).update(
            workspace_id=workspace.pk
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_workspace_rbac_schema'),
    ]

    operations = [migrations.RunPython(backfill_personal_workspaces, migrations.RunPython.noop)]
