# Generated by Django 5.2.6 on 2026-09-10 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_backfill_personal_workspaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='api.workspace'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_bases', to='api.workspace'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_configs', to='api.workspace'),
        ),
    ]
