# Generated by Django 5.2.6 on 2026-09-11 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.db import migrations, models


def backfill_account_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    AccountProfile = apps.get_model('api', 'AccountProfile')
    candidates = []
    counts = {}
    for user in User.objects.all().iterator():
        email = (user.email or '').strip().lower()
        try:
            if email:
                validate_email(email)
        except ValidationError:
            email = ''
        candidates.append((user.pk, email))
        if email:
            counts[email] = counts.get(email, 0) + 1
    AccountProfile.objects.bulk_create([
        AccountProfile(user_id=user_id, normalized_email=email if counts.get(email) == 1 else None)
        for user_id, email in candidates
    ])


def reverse_profiles(apps, schema_editor):
    apps.get_model('api', 'AccountProfile').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_enforce_workspace_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_key_digest', models.CharField(max_length=64, unique=True)),
                ('user_agent_summary', models.CharField(blank=True, default='', max_length=200)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_normalized', models.EmailField(max_length=254)),
                ('organization_role', models.CharField(choices=[('OWNER', '所有者'), ('ADMIN', '管理员'), ('MEMBER', '成员'), ('AUDITOR', '审计员')], default='MEMBER', max_length=20)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', '待接受'), ('ACCEPTED', '已接受'), ('REVOKED', '已撤销'), ('EXPIRED', '已过期')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_organization_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_organization_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvitationWorkspaceGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_role', models.CharField(choices=[('ADMIN', '管理员'), ('DEVELOPER', '开发者'), ('OPERATOR', '运营者'), ('VIEWER', '查看者'), ('AUDITOR', '审计员')], default='VIEWER', max_length=20)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_grants', to='api.workspace')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_grants', to='api.organizationinvitation')),
            ],
            options={
                'ordering': ['workspace_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='organizationinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('organization', 'email_normalized'), name='unique_pending_organization_invitation'),
        ),
        migrations.AddConstraint(
            model_name='invitationworkspacegrant',
            constraint=models.UniqueConstraint(fields=('invitation', 'workspace'), name='unique_invitation_workspace_grant'),
        ),
        migrations.RunPython(backfill_account_profiles, reverse_profiles),
    ]
