# Generated by Django 5.2.6 on 2026-09-15 05:10

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


def create_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('CREATE EXTENSION IF NOT EXISTS vector')


def keep_shared_vector_extension(apps, schema_editor):
    # pgvector may be shared by other applications; rolling this app back must not drop it.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_accountprofile_accountsession_organizationinvitation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_vector_extension, keep_shared_vector_extension),
        migrations.CreateModel(
            name='EmbeddingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=160)),
                ('model_name', models.CharField(max_length=200)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('dimension', models.PositiveIntegerField()),
                ('distance_metric', models.CharField(choices=[('COSINE', '余弦距离')], default='COSINE', max_length=20)),
                ('status', models.CharField(choices=[('DISCOVERED', '已发现'), ('BUILDING', '构建中'), ('READY', '可用'), ('DEGRADED', '降级'), ('RETIRED', '已停用')], default='DISCOVERED', max_length=20)),
                ('indexed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embedding_spaces', to='api.modelconfig')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_spaces', to='api.workspace')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParagraphEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField()),
                ('dimension', models.PositiveIntegerField()),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_embeddings', to='api.paragraph')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_embeddings', to='api.embeddingspace')),
            ],
        ),
        migrations.CreateModel(
            name='VectorMigrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '等待迁移'), ('RUNNING', '迁移中'), ('SUCCESS', '迁移成功'), ('FAILURE', '迁移失败'), ('CANCEL_REQUESTED', '正在取消'), ('CANCELLED', '已取消')], default='PENDING', max_length=30)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('succeeded_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('cursor_id', models.PositiveBigIntegerField(default=0)),
                ('batch_size', models.PositiveSmallIntegerField(default=200)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vector_migrations', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='migration_runs', to='api.embeddingspace')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_migrations', to='api.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='embeddingspace',
            constraint=models.UniqueConstraint(fields=('workspace', 'signature', 'dimension'), name='unique_workspace_embedding_space'),
        ),
        migrations.AddConstraint(
            model_name='embeddingspace',
            constraint=models.CheckConstraint(condition=models.Q(('dimension__gte', 1)), name='embedding_space_dimension_positive'),
        ),
        migrations.AddIndex(
            model_name='paragraphembedding',
            index=models.Index(fields=['space', 'dimension'], name='paragraph_space_dimension_idx'),
        ),
        migrations.AddConstraint(
            model_name='paragraphembedding',
            constraint=models.UniqueConstraint(fields=('paragraph', 'space'), name='unique_paragraph_embedding_space'),
        ),
        migrations.AddConstraint(
            model_name='paragraphembedding',
            constraint=models.CheckConstraint(condition=models.Q(('dimension__gte', 1)), name='paragraph_embedding_dimension_positive'),
        ),
        migrations.AddConstraint(
            model_name='vectormigrationrun',
            constraint=models.CheckConstraint(condition=models.Q(('batch_size__gte', 10), ('batch_size__lte', 2000)), name='vector_migration_batch_size_range'),
        ),
    ]
