# Generated by Django 5.2.6 on 2026-09-15 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_embeddingspace_paragraphembedding_vectormigrationrun_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vectormigrationrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'RUNNING', 'CANCEL_REQUESTED'))), fields=('space',), name='unique_active_vector_migration_space'),
        ),
    ]
