# Generated by Django 5.2.6 on 2026-09-15 08:06

import django.db.models.deletion
from django.db import migrations, models


def backfill_knowledge_base(apps, schema_editor):
    ParagraphEmbedding = apps.get_model('api', 'ParagraphEmbedding')
    rows = []
    queryset = (
        ParagraphEmbedding.objects.filter(knowledge_base__isnull=True)
        .select_related('paragraph__document')
        .iterator(chunk_size=1000)
    )
    for row in queryset:
        row.knowledge_base_id = row.paragraph.document.knowledge_base_id
        rows.append(row)
        if len(rows) == 1000:
            ParagraphEmbedding.objects.bulk_update(rows, ['knowledge_base'], batch_size=1000)
            rows.clear()
    if rows:
        ParagraphEmbedding.objects.bulk_update(rows, ['knowledge_base'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_vectormigrationrun_unique_active_vector_migration_space'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paragraphembedding',
            name='paragraph_space_dimension_idx',
        ),
        migrations.AddField(
            model_name='paragraphembedding',
            name='knowledge_base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_embeddings', to='api.knowledgebase'),
        ),
        migrations.RunPython(backfill_knowledge_base, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='paragraphembedding',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_embeddings', to='api.knowledgebase'),
        ),
        migrations.AddIndex(
            model_name='paragraphembedding',
            index=models.Index(fields=['knowledge_base', 'space', 'dimension'], name='paragraph_kb_space_dim_idx'),
        ),
    ]
